<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="Sara Jesperson and Sara Johansson" />

<meta name="date" content="2017-10-14" />

<title>lab-7: The ridgereg package</title>



<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>



<link href="data:text/css;charset=utf-8,body%20%7B%0Abackground%2Dcolor%3A%20%23fff%3B%0Amargin%3A%201em%20auto%3B%0Amax%2Dwidth%3A%20700px%3B%0Aoverflow%3A%20visible%3B%0Apadding%2Dleft%3A%202em%3B%0Apadding%2Dright%3A%202em%3B%0Afont%2Dfamily%3A%20%22Open%20Sans%22%2C%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20Arial%2C%20sans%2Dserif%3B%0Afont%2Dsize%3A%2014px%3B%0Aline%2Dheight%3A%201%2E35%3B%0A%7D%0A%23header%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0A%23TOC%20%7B%0Aclear%3A%20both%3B%0Amargin%3A%200%200%2010px%2010px%3B%0Apadding%3A%204px%3B%0Awidth%3A%20400px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Aborder%2Dradius%3A%205px%3B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Afont%2Dsize%3A%2013px%3B%0Aline%2Dheight%3A%201%2E3%3B%0A%7D%0A%23TOC%20%2Etoctitle%20%7B%0Afont%2Dweight%3A%20bold%3B%0Afont%2Dsize%3A%2015px%3B%0Amargin%2Dleft%3A%205px%3B%0A%7D%0A%23TOC%20ul%20%7B%0Apadding%2Dleft%3A%2040px%3B%0Amargin%2Dleft%3A%20%2D1%2E5em%3B%0Amargin%2Dtop%3A%205px%3B%0Amargin%2Dbottom%3A%205px%3B%0A%7D%0A%23TOC%20ul%20ul%20%7B%0Amargin%2Dleft%3A%20%2D2em%3B%0A%7D%0A%23TOC%20li%20%7B%0Aline%2Dheight%3A%2016px%3B%0A%7D%0Atable%20%7B%0Amargin%3A%201em%20auto%3B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dcolor%3A%20%23DDDDDD%3B%0Aborder%2Dstyle%3A%20outset%3B%0Aborder%2Dcollapse%3A%20collapse%3B%0A%7D%0Atable%20th%20%7B%0Aborder%2Dwidth%3A%202px%3B%0Apadding%3A%205px%3B%0Aborder%2Dstyle%3A%20inset%3B%0A%7D%0Atable%20td%20%7B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dstyle%3A%20inset%3B%0Aline%2Dheight%3A%2018px%3B%0Apadding%3A%205px%205px%3B%0A%7D%0Atable%2C%20table%20th%2C%20table%20td%20%7B%0Aborder%2Dleft%2Dstyle%3A%20none%3B%0Aborder%2Dright%2Dstyle%3A%20none%3B%0A%7D%0Atable%20thead%2C%20table%20tr%2Eeven%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Ap%20%7B%0Amargin%3A%200%2E5em%200%3B%0A%7D%0Ablockquote%20%7B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Apadding%3A%200%2E25em%200%2E75em%3B%0A%7D%0Ahr%20%7B%0Aborder%2Dstyle%3A%20solid%3B%0Aborder%3A%20none%3B%0Aborder%2Dtop%3A%201px%20solid%20%23777%3B%0Amargin%3A%2028px%200%3B%0A%7D%0Adl%20%7B%0Amargin%2Dleft%3A%200%3B%0A%7D%0Adl%20dd%20%7B%0Amargin%2Dbottom%3A%2013px%3B%0Amargin%2Dleft%3A%2013px%3B%0A%7D%0Adl%20dt%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Aul%20%7B%0Amargin%2Dtop%3A%200%3B%0A%7D%0Aul%20li%20%7B%0Alist%2Dstyle%3A%20circle%20outside%3B%0A%7D%0Aul%20ul%20%7B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Apre%2C%20code%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0Aborder%2Dradius%3A%203px%3B%0Acolor%3A%20%23333%3B%0Awhite%2Dspace%3A%20pre%2Dwrap%3B%20%0A%7D%0Apre%20%7B%0Aborder%2Dradius%3A%203px%3B%0Amargin%3A%205px%200px%2010px%200px%3B%0Apadding%3A%2010px%3B%0A%7D%0Apre%3Anot%28%5Bclass%5D%29%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Acode%20%7B%0Afont%2Dfamily%3A%20Consolas%2C%20Monaco%2C%20%27Courier%20New%27%2C%20monospace%3B%0Afont%2Dsize%3A%2085%25%3B%0A%7D%0Ap%20%3E%20code%2C%20li%20%3E%20code%20%7B%0Apadding%3A%202px%200px%3B%0A%7D%0Adiv%2Efigure%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0Aimg%20%7B%0Abackground%2Dcolor%3A%20%23FFFFFF%3B%0Apadding%3A%202px%3B%0Aborder%3A%201px%20solid%20%23DDDDDD%3B%0Aborder%2Dradius%3A%203px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Amargin%3A%200%205px%3B%0A%7D%0Ah1%20%7B%0Amargin%2Dtop%3A%200%3B%0Afont%2Dsize%3A%2035px%3B%0Aline%2Dheight%3A%2040px%3B%0A%7D%0Ah2%20%7B%0Aborder%2Dbottom%3A%204px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Apadding%2Dbottom%3A%202px%3B%0Afont%2Dsize%3A%20145%25%3B%0A%7D%0Ah3%20%7B%0Aborder%2Dbottom%3A%202px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Afont%2Dsize%3A%20120%25%3B%0A%7D%0Ah4%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23f7f7f7%3B%0Amargin%2Dleft%3A%208px%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Ah5%2C%20h6%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23ccc%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Aa%20%7B%0Acolor%3A%20%230033dd%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Aa%3Ahover%20%7B%0Acolor%3A%20%236666ff%3B%20%7D%0Aa%3Avisited%20%7B%0Acolor%3A%20%23800080%3B%20%7D%0Aa%3Avisited%3Ahover%20%7B%0Acolor%3A%20%23BB00BB%3B%20%7D%0Aa%5Bhref%5E%3D%22http%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0Aa%5Bhref%5E%3D%22https%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0A%0Acode%20%3E%20span%2Ekw%20%7B%20color%3A%20%23555%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Edt%20%7B%20color%3A%20%23902000%3B%20%7D%20%0Acode%20%3E%20span%2Edv%20%7B%20color%3A%20%2340a070%3B%20%7D%20%0Acode%20%3E%20span%2Ebn%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Efl%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Ech%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Est%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Eco%20%7B%20color%3A%20%23888888%3B%20font%2Dstyle%3A%20italic%3B%20%7D%20%0Acode%20%3E%20span%2Eot%20%7B%20color%3A%20%23007020%3B%20%7D%20%0Acode%20%3E%20span%2Eal%20%7B%20color%3A%20%23ff0000%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Efu%20%7B%20color%3A%20%23900%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%20code%20%3E%20span%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%20%0A" rel="stylesheet" type="text/css" />

</head>

<body>




<h1 class="title toc-ignore">lab-7: The ridgereg package</h1>
<h4 class="author"><em>Sara Jesperson and Sara Johansson</em></h4>
<h4 class="date"><em>2017-10-14</em></h4>



<p>This vignette will show how to do a simple prediction using the <code>ridgereg()</code> class from the package lab7sarasara. In this vignette, the caret package will also be used as well as the data set BostonHousing from the mlbench package.</p>
<div id="partitioning-data" class="section level2">
<h2>Partitioning data</h2>
<p>The BostonHousing data set can be partitioned into a training and test set in the following way. The variable medv is chosen as the dependent variable.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">12345</span>)
train_index &lt;-<span class="st"> </span><span class="kw">createDataPartition</span>(<span class="dt">y =</span> BostonHousing<span class="op">$</span>medv, <span class="dt">p =</span> <span class="fl">0.75</span>, <span class="dt">list =</span> <span class="ot">FALSE</span>)
training &lt;-<span class="st"> </span>BostonHousing[train_index,]
testing &lt;-<span class="st"> </span>BostonHousing[<span class="op">-</span>train_index,]</code></pre></div>
<p>The data has now been divided into a training and a test data set.</p>
</div>
<div id="linear-regression-and-model-evaluation" class="section level2">
<h2>Linear regression and model evaluation</h2>
<div id="lm-method" class="section level3">
<h3>lm method</h3>
<p>A linear regression model on the training function can be fitted with the <code>train()</code> function from the caret package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">12345</span>)

(lm1 &lt;-<span class="st"> </span>caret<span class="op">::</span><span class="kw">train</span>(medv <span class="op">~</span><span class="st"> </span>., <span class="dt">data=</span>training, <span class="dt">method =</span> <span class="st">'lm'</span>))</code></pre></div>
<pre><code>Linear Regression 

381 samples
 13 predictor

No pre-processing
Resampling: Bootstrapped (25 reps) 
Summary of sample sizes: 381, 381, 381, 381, 381, 381, ... 
Resampling results:

  RMSE      Rsquared   MAE     
  5.006581  0.6893835  3.486857

Tuning parameter 'intercept' was held constant at a value of TRUE</code></pre>
<p>All covariates were used in the model estimation, and the only coefficients not significant were those for variables crim, indus and age. The RMSE value for the model is 5.01, the MAE value is 3.49 and <span class="math inline">\(R^2\)</span> is 68.9 percent.</p>
</div>
<div id="leapforward-method" class="section level3">
<h3>leapForward method</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">12345</span>)

(lm2 &lt;-<span class="st"> </span>caret<span class="op">::</span><span class="kw">train</span>(medv <span class="op">~</span><span class="st"> </span>., <span class="dt">data=</span>training, <span class="dt">method =</span> <span class="st">'leapForward'</span>))</code></pre></div>
<pre><code>Linear Regression with Forward Selection 

381 samples
 13 predictor

No pre-processing
Resampling: Bootstrapped (25 reps) 
Summary of sample sizes: 381, 381, 381, 381, 381, 381, ... 
Resampling results across tuning parameters:

  nvmax  RMSE      Rsquared   MAE     
  2      5.689017  0.6029970  4.033465
  3      5.528423  0.6226443  3.838150
  4      5.457338  0.6336603  3.756693

RMSE was used to select the optimal model using  the smallest value.
The final value used for the model was nvmax = 4.</code></pre>
<p>As it can be seen in the printout above, the final value used for nvmax is 4. The independent variables used in the final model are rm, ptratio, b and lstat, which can be seen in the printout below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(lm2)<span class="op">$</span>which</code></pre></div>
<pre><code>  (Intercept)  crim    zn indus chas1   nox    rm   age   dis   rad   tax
1        TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
2        TRUE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
3        TRUE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
4        TRUE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
  ptratio     b lstat
1   FALSE FALSE  TRUE
2   FALSE FALSE  TRUE
3    TRUE FALSE  TRUE
4    TRUE  TRUE  TRUE</code></pre>
<p>The final model with four variables has a RMSE value of 5.46, a MAE of 3.76 and <span class="math inline">\(R^2\)</span> is 63,4 percent.</p>
</div>
<div id="evaluation" class="section level3">
<h3>Evaluation</h3>
<p>The first model with the ‘lm’ method has a better RMSE and MAE value which indicates a better performance with the first model.</p>
</div>
</div>
<div id="custom-model-and-10-fold-cross-validation" class="section level2">
<h2>Custom model and 10-fold cross-validation</h2>
<p>The ridgereg() reference class from the lab7sarasara package is used as a custom model when fitting a ridge regression model on the BostonHousing data. To use the <code>ridgereg()</code> function as a custom function, the following list should be used. Four lambda values are tested.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ridge &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">type=</span><span class="st">&quot;Regression&quot;</span>, 
              <span class="dt">library=</span><span class="st">&quot;lab7&quot;</span>,
              <span class="dt">loop=</span><span class="ot">NULL</span>,
              <span class="dt">prob=</span><span class="ot">NULL</span>)
ridge<span class="op">$</span>parameters &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">parameter=</span><span class="st">&quot;lambda&quot;</span>,
                               <span class="dt">class=</span><span class="st">&quot;numeric&quot;</span>,
                               <span class="dt">label=</span><span class="st">&quot;lambda&quot;</span>)
ridge<span class="op">$</span>grid &lt;-<span class="st"> </span><span class="cf">function</span>(y,x, <span class="dt">len=</span><span class="ot">NULL</span>, <span class="dt">search=</span><span class="st">&quot;grid&quot;</span>){
  <span class="kw">data.frame</span>(<span class="dt">lambda=</span><span class="kw">c</span>(<span class="fl">0.1</span>,<span class="fl">0.5</span>,<span class="dv">1</span>,<span class="dv">2</span>))
}
ridge<span class="op">$</span>fit &lt;-<span class="st"> </span><span class="cf">function</span> (x, y, wts, param, lev, last, classProbs, ...) {
  dat &lt;-<span class="st"> </span><span class="cf">if</span> (<span class="kw">is.data.frame</span>(x)) 
    x
  <span class="cf">else</span> <span class="kw">as.data.frame</span>(x)
  dat<span class="op">$</span>.outcome &lt;-<span class="st"> </span>y
  out &lt;-<span class="st"> </span>ridgereg<span class="op">$</span><span class="kw">new</span>(.outcome <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> dat, <span class="dt">lambda=</span>param<span class="op">$</span>lambda, ...)
  out
}
ridge<span class="op">$</span>predict &lt;-<span class="st"> </span><span class="cf">function</span> (modelFit, newdata, <span class="dt">submodels =</span> <span class="ot">NULL</span>) {
  <span class="cf">if</span> (<span class="op">!</span><span class="kw">is.data.frame</span>(newdata)) 
    newdata &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(newdata)
  newdata[,<span class="kw">apply</span>(newdata, <span class="dt">MARGIN=</span><span class="dv">2</span>, sd)<span class="op">!=</span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="kw">scale</span>(newdata[,<span class="kw">apply</span>(newdata, <span class="dt">MARGIN=</span><span class="dv">2</span>, sd)<span class="op">!=</span><span class="dv">0</span>])
  modelFit<span class="op">$</span><span class="kw">predict</span>(newdata)
}</code></pre></div>
<p>To use 10-fold cross-validation on the training set, the following code is needed.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">control &lt;-<span class="st"> </span><span class="kw">trainControl</span>(<span class="dt">method =</span> <span class="st">&quot;repeatedcv&quot;</span>,
                        <span class="dt">number=</span><span class="dv">10</span>,
                        <span class="dt">repeats =</span> <span class="dv">10</span>)</code></pre></div>
<p>At last, the ridge regression can be used on the training set with the code below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">12345</span>)
(lm.ridge &lt;-<span class="st"> </span><span class="kw">train</span>(medv <span class="op">~</span><span class="st"> </span>., <span class="dt">data=</span>training, <span class="dt">method=</span>ridge, <span class="dt">trControl=</span>control))</code></pre></div>
<pre><code>381 samples
 13 predictor

No pre-processing
Resampling: Cross-Validated (10 fold, repeated 10 times) 
Summary of sample sizes: 341, 343, 342, 343, 342, 344, ... 
Resampling results across tuning parameters:

  lambda  RMSE      Rsquared   MAE     
  0.1     4.870437  0.7077585  3.422627
  0.5     4.869391  0.7078084  3.415994
  1.0     4.868411  0.7078592  3.408006
  2.0     4.867487  0.7079275  3.393183

RMSE was used to select the optimal model using  the smallest value.
The final value used for the model was lambda = 2.</code></pre>
<p>The best <span class="math inline">\(\lambda\)</span> value, found with 10-fold cross-validation on the training set, is <span class="math inline">\(\lambda=2\)</span>, which can be seen in the printout above. The RMSE for this model is lower than the two previous models.</p>
</div>
<div id="model-evaluation" class="section level2">
<h2>Model evaluation</h2>
<p>The performance of all three models are evaluated on the test set by computing the RMSE, <span class="math inline">\(R^2\)</span> and MAE.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Linear regression</span>
<span class="kw">set.seed</span>(<span class="dv">12345</span>)
test_lm1 &lt;-<span class="st"> </span><span class="kw">predict</span>(lm1, testing)
<span class="kw">postResample</span>(<span class="dt">pred=</span>test_lm1, <span class="dt">obs=</span>testing<span class="op">$</span>medv )</code></pre></div>
<pre><code>##      RMSE  Rsquared       MAE 
## 4.8801009 0.7822387 3.4029401</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Linear regression leap forward</span>
<span class="kw">set.seed</span>(<span class="dv">12345</span>)
test_lm2 &lt;-<span class="st"> </span><span class="kw">predict</span>(lm2, testing)
<span class="kw">postResample</span>(<span class="dt">pred=</span>test_lm2, <span class="dt">obs=</span>testing<span class="op">$</span>medv )</code></pre></div>
<pre><code>##      RMSE  Rsquared       MAE 
## 5.2134850 0.7502851 3.6010839</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Ridge regression</span>
<span class="kw">set.seed</span>(<span class="dv">12345</span>)
test_ridge &lt;-<span class="st"> </span><span class="kw">predict</span>(lm.ridge, testing)
<span class="kw">postResample</span>(<span class="dt">pred=</span>test_ridge, <span class="dt">obs=</span>testing<span class="op">$</span>medv )</code></pre></div>
<pre><code>##      RMSE  Rsquared       MAE 
## 4.9755827 0.7828446 3.4364333</code></pre>
<p>From the output it can be concluded that, when evaluated on the test set, the linear reression performs the best.</p>
</div>



<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
